# This file was generated by GoReleaser. DO NOT EDIT.
cask "dbui" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "38f17699ecb739961ca0c8cff6ee9a4f54b8d9200baf89e92b24d6b4f0b209cf"
      url "https://github.com/KenanBek/dbui/releases/download/v0.9.0/dbui_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1db9d60de46496779564e68deb3b80c5307d06dbc7716b2d23553c65ea7ba6c5"
      url "https://github.com/KenanBek/dbui/releases/download/v0.9.0/dbui_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e68953ab928d1db82bc13a6b36e46f127aa52034d236f8657d8a0a97e525c880"
      url "https://github.com/KenanBek/dbui/releases/download/v0.9.0/dbui_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4d07095e3f887dce9d039f6a4358f894ab74c49da598658a70d063f710140d32"
      url "https://github.com/KenanBek/dbui/releases/download/v0.9.0/dbui_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dbui"
  desc "Terminal UI for MySQL, PostgreSQL, and SQLite."
  homepage "https://github.com/kenanbek/dbui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dbui"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dbui"]
    end
  end

  # No zap stanza required

end
